/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nomnom;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author lisas
 */
public class LaggTillMatvara extends javax.swing.JFrame {
    private InfDB idb;
    private LaggTillMatratt laggTillMatratt;
    /**
     * Creates new form LaggTillMatvara
     */
    public LaggTillMatvara(InfDB idb, LaggTillMatratt laggTillMatratt) {
        initComponents();
        this.idb = idb;
        this.laggTillMatratt = laggTillMatratt;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVara = new javax.swing.JLabel();
        lblEnhet = new javax.swing.JLabel();
        tfVara = new javax.swing.JTextField();
        tfEnhet = new javax.swing.JTextField();
        btnSpara = new javax.swing.JButton();
        lblBastFore = new javax.swing.JLabel();
        lblTyp = new javax.swing.JLabel();
        tfBastFore = new javax.swing.JTextField();
        tfTyp = new javax.swing.JTextField();
        lblPPE = new javax.swing.JLabel();
        tfPPE = new javax.swing.JTextField();
        lblMangd = new javax.swing.JLabel();
        tfMangd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVara.setText("Vara");

        lblEnhet.setText("Enhet");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        lblBastFore.setText("Bäst Före");

        lblTyp.setText("Typ");

        lblPPE.setText("Pris/Enhet");

        lblMangd.setText("Mängd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblEnhet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblVara, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(btnSpara)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTyp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPPE)
                            .addComponent(lblBastFore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMangd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfVara, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfEnhet, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfBastFore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTyp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPPE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfMangd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVara)
                    .addComponent(tfVara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnhet)
                    .addComponent(tfEnhet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMangd)
                    .addComponent(tfMangd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfBastFore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBastFore))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPPE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTyp))
                .addGap(42, 42, 42)
                .addComponent(btnSpara)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        
            //Hämta vad som står i textfälten
            String vara = tfVara.getText();
            String enhet = tfEnhet.getText();
            String textMangd = tfMangd.getText();
            String textBastFore = tfBastFore.getText();
            String textPrisPerEnhet = tfPPE.getText();
            String typ = tfTyp.getText();
            
            if(Validering.arGiltigtDouble(textPrisPerEnhet) && Validering.valideringDatum(textBastFore) && Validering.faltInteTomt(vara) && Validering.faltInteTomt(enhet) && Validering.faltInteTomt(textBastFore) && Validering.faltInteTomt(textPrisPerEnhet) && Validering.faltInteTomt(typ)){
                
                try{
                    double mangd = Double.parseDouble(textMangd);
                    LocalDate bastFore = LocalDate.parse(textBastFore);
                    double prisPerEnhet = Double.parseDouble(textPrisPerEnhet);
                    
                    String insertMatvara = "insert into matvaror (Vara, Enhet, Mangd, BastFore, PrisPerEnhet) values ('" + vara + "', '" + enhet + "', " + mangd + ", '" + bastFore + "', " + prisPerEnhet + ");";
                    idb.insert(insertMatvara);
                    
                    String selectMid = "select MatvaruID from matvaror where Vara = '" + vara + "';";
                    String ettMid = idb.fetchSingle(selectMid);
                    
                    if(typ.toLowerCase().contains("kyl")){
                        String insertIntoKyl = "insert into kylvaror (MatvaruID) values ('" + ettMid + "');";
                        idb.insert(insertIntoKyl);
                    }
                            
                    else if(typ.toLowerCase().contains("frys")){
                        String insertIntoFrys = "insert into frysvaror (MatvaruID) values ('" + ettMid + "');";
                        idb.insert(insertIntoFrys);
                    }
                        
                    else if(typ.toLowerCase().contains("skafferi")){
                        String insertIntoSkafferi = "insert into skafferi (MatvaruID) values ('" + ettMid + "');";
                        idb.insert(insertIntoSkafferi);
                    }
                                  
                    else{
                        JOptionPane.showMessageDialog(null, "Fyll i något vettigt, idiot");
                    }
                    System.out.println("Här!");
                    laggTillMatratt.fyllVaraComboBox();
                    JOptionPane.showMessageDialog(null, "Matvaran har lagts till!"); 
                    this.dispose();
                }   
                catch(DateTimeParseException | NumberFormatException | InfException ex){
                    JOptionPane.showMessageDialog(null, "Fel!");
                }   
        }
        
    }//GEN-LAST:event_btnSparaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillMatvara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillMatvara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillMatvara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillMatvara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           //     new LaggTillMatvara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JLabel lblBastFore;
    private javax.swing.JLabel lblEnhet;
    private javax.swing.JLabel lblMangd;
    private javax.swing.JLabel lblPPE;
    private javax.swing.JLabel lblTyp;
    private javax.swing.JLabel lblVara;
    private javax.swing.JTextField tfBastFore;
    private javax.swing.JTextField tfEnhet;
    private javax.swing.JTextField tfMangd;
    private javax.swing.JTextField tfPPE;
    private javax.swing.JTextField tfTyp;
    private javax.swing.JTextField tfVara;
    // End of variables declaration//GEN-END:variables
}
