/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nomnom;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author lisas
 */
public class Matvaror extends javax.swing.JPanel {
private InfDB idb;
    /**
     * Creates new form Matvaror
     */
    public Matvaror(InfDB idb) {
        initComponents();
        this.idb = idb;
        fyllTabell();
    }
    
    public void fyllTabell(){
        try{
            String kolumnNamn[] = {"Vara", "Mangd", "Enhet", "BastFore", "PrisPerEnhet"};

            DefaultTableModel allaMatvaror = new DefaultTableModel(kolumnNamn, 0);
            
            String selectMID = "select MatvaruID from Matvaror order by(Vara);";
            ArrayList<String> mid = idb.fetchColumn(selectMID);
            
            if(mid != null){
                for(String ettMid:mid){
                    String selectMatvaror = "select Vara, Enhet, Mangd, BastFore, PrisPerEnhet from Matvaror where MatvaruID = " + ettMid + ";";
                    HashMap<String,String> matvaror = idb.fetchRow(selectMatvaror);               
                    
                    Object[] enRad = new Object[kolumnNamn.length];
                    int index = 0;
                    
                    for(String enKolumn:kolumnNamn){
                        enRad[index++] = matvaror.get(enKolumn);
                    }
                    allaMatvaror.addRow(enRad);
                }
                tblAllaMatvaror.setModel(allaMatvaror);
            }
            tblAllaMatvaror.getColumnModel().getColumn(0).setHeaderValue("Vara");
            tblAllaMatvaror.getColumnModel().getColumn(1).setHeaderValue("Mängd");
            tblAllaMatvaror.getColumnModel().getColumn(2).setHeaderValue("Enhet");
            tblAllaMatvaror.getColumnModel().getColumn(3).setHeaderValue("Bäst Före");
            tblAllaMatvaror.getColumnModel().getColumn(4).setHeaderValue("Pris/Enhet");
        }
        catch(InfException ex){
            JOptionPane.showMessageDialog(null, "Fel vid databasåtkomst!");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllaMatvaror = new javax.swing.JTable();
        btnSpara = new javax.swing.JButton();
        btnLaggTill = new javax.swing.JButton();
        btnTaBort = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblAllaMatvaror.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tblAllaMatvaror);

        btnSpara.setText("Spara");

        btnLaggTill.setText("Lägg till");
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("MATVAROR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnLaggTill)
                            .addGap(18, 18, 18)
                            .addComponent(btnTaBort)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSpara))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLaggTill)
                    .addComponent(btnTaBort)
                    .addComponent(btnSpara))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        new LaggTillMatvara(idb).setVisible(true);
    }//GEN-LAST:event_btnLaggTillActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        try{
            int valdRad = tblAllaMatvaror.getSelectedRow();
            
            if(valdRad == -1){
                JOptionPane.showMessageDialog(null, "Välj en rad för att ta bort");
                return;
            }
            
            String vara = tblAllaMatvaror.getValueAt(valdRad, 0).toString();
            
            String selectMid = "select MatvaruID from matvaror where Vara = '" + vara + "';";
            String ettMid = idb.fetchSingle(selectMid);
            
            int val = JOptionPane.showConfirmDialog(this, "Vill du verkligen ta bort matvaran?", "Bekräfta", JOptionPane.YES_NO_OPTION);
            
            if(val == JOptionPane.YES_OPTION){
                idb.delete("delete from kylvaror where MatvaruID = '" + ettMid + "';");
                idb.delete("delete from frysvaror where MatvaruID = '" + ettMid + "';");
                idb.delete("delete from skafferi where MatvaruID = '" + ettMid + "';");
                idb.delete("delete from Matratt_Matvara where MatvaruID = '" + ettMid + "';");
                 
                String taBort = "delete from matvaror where MatvaruID = '" + ettMid + "';";
                idb.delete(taBort);
                
                fyllTabell();
                
                JOptionPane.showMessageDialog(null, "Matvaran borttagen :)");
            }
   /*         
            String selectMidKyl = "select MatvaruID from kylvaror where MatvaruID = '" + ettMid + "';";
            String selectMidFrys = "select MatvaruID from frysvaror where MatvaruID = '" + ettMid + "';";
            String selectMidSkafferi = "select MatvaruID from skafferi where MatvaruID = '" + ettMid + "';";
            
            String midKyl = idb.fetchSingle(selectMidKyl);
            String midFrys = idb.fetchSingle(selectMidFrys);
            String midSkafferi = idb.fetchSingle(selectMidSkafferi);
                    
            if(val == JOptionPane.YES_OPTION && midKyl != null){
                String taBortKyl = "delete from kylvaror where MatvaruID = '" + midKyl + "';";
                idb.delete(taBortKyl);
            }
            else if(val == JOptionPane.YES_OPTION && midFrys != null){
                String taBortFrys = "delete from frysvaror where MatvaruID = '" + midFrys + "';";
                idb.delete(taBortFrys);
            }
            else if(val == JOptionPane.YES_OPTION && midSkafferi != null){
                String taBortSkafferi = "delete from skafferi where MatvaruID = '" + midSkafferi + "';";
                idb.delete(taBortSkafferi);
            }*/
        }
        catch(InfException ex){
            JOptionPane.showMessageDialog(null, "FEL!!" + ex.getMessage());
        }
    }//GEN-LAST:event_btnTaBortActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAllaMatvaror;
    // End of variables declaration//GEN-END:variables
}
