/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nomnom;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author limme
 */
public class SeMatratt extends javax.swing.JPanel {
private InfDB idb;
private String klickadMatratt;
    /**
     * Creates new form Matvaror
     */
    public SeMatratt(InfDB idb, String klickadMatratt) {
        initComponents();
        this.idb = idb;
        this.klickadMatratt = klickadMatratt;
        infoOmMatratt();
        fyllTabell();
    }

    public void infoOmMatratt(){
        lblRatt.setText(klickadMatratt);
        try{
            String selectInfoOmMatratt = "select Portioner, Tillagningstid, Kostnad, HeadChef from Matratter where Ratt = '" + klickadMatratt + "';";
            HashMap<String,String> infoOmMatratt = idb.fetchRow(selectInfoOmMatratt);
             
            lblTid.setText("Tillagningstid: " + infoOmMatratt.get("Tillagningstid") + " min");
            lblPortioner.setText("Antal portioner: " + infoOmMatratt.get("Portioner"));
            lblKostnad.setText("Kostnad: " + infoOmMatratt.get("Kostnad") + " kr");
            lblHeadChef.setText("Head Chef: " + infoOmMatratt.get("HeadChef"));
        }
        catch(InfException ex){
            JOptionPane.showMessageDialog(this, "Fel");
        }
    }
    
    public void fyllTabell(){
        try{
            String kolumnNamn[] = {"Vara", "Mangd", "Enhet", "PrisPerEnhet"};

            DefaultTableModel varorIMatratt = new DefaultTableModel(kolumnNamn, 0);
            
            String selectMID = "select MatvaruID from Matratt_Matvara where MatrattsID = (select MatrattsID from Matratter where Ratt = '" + klickadMatratt + "');";
            ArrayList<String> mid = idb.fetchColumn(selectMID);
            
            if(mid != null){
                for(String ettMid:mid){
                    String selectMatvaror = "select Vara, Enhet, Mangd, PrisPerEnhet from Matvaror where MatvaruID = " + ettMid + ";";
                    HashMap<String,String> matvaror = idb.fetchRow(selectMatvaror);               
                    
                    Object[] enRad = new Object[kolumnNamn.length];
                    int index = 0;
                    
                    for(String enKolumn:kolumnNamn){
                        enRad[index++] = matvaror.get(enKolumn);
                    }
                    varorIMatratt.addRow(enRad);
                }
                tblMatvaror.setModel(varorIMatratt);
            }
            tblMatvaror.getColumnModel().getColumn(0).setHeaderValue("Vara");
            tblMatvaror.getColumnModel().getColumn(1).setHeaderValue("Mängd");
            tblMatvaror.getColumnModel().getColumn(2).setHeaderValue("Enhet");
            tblMatvaror.getColumnModel().getColumn(3).setHeaderValue("Pris/Enhet");
        }
        catch(InfException ex){
            JOptionPane.showMessageDialog(null, "Fel vid databasåtkomst!");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRatt = new javax.swing.JLabel();
        lblPortioner = new javax.swing.JLabel();
        lblTid = new javax.swing.JLabel();
        lblKostnad = new javax.swing.JLabel();
        lblHeadChef = new javax.swing.JLabel();
        btnInkopslista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatvaror = new javax.swing.JTable();
        lblMatvaror = new javax.swing.JLabel();

        lblRatt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRatt.setText("jLabel1");

        lblPortioner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPortioner.setText("jLabel1");

        lblTid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTid.setText("jLabel1");

        lblKostnad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKostnad.setText("jLabel1");

        lblHeadChef.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHeadChef.setText("jLabel1");

        btnInkopslista.setText("Lägg till i inköpslista");

        tblMatvaror.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMatvaror);

        lblMatvaror.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMatvaror.setText("Matvaror");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRatt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInkopslista))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMatvaror)
                            .addComponent(lblPortioner)
                            .addComponent(lblTid)
                            .addComponent(lblKostnad)
                            .addComponent(lblHeadChef))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInkopslista)
                    .addComponent(lblRatt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPortioner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKostnad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHeadChef)
                .addGap(18, 18, 18)
                .addComponent(lblMatvaror)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInkopslista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeadChef;
    private javax.swing.JLabel lblKostnad;
    private javax.swing.JLabel lblMatvaror;
    private javax.swing.JLabel lblPortioner;
    private javax.swing.JLabel lblRatt;
    private javax.swing.JLabel lblTid;
    private javax.swing.JTable tblMatvaror;
    // End of variables declaration//GEN-END:variables
}
